DapperSampleProject/Models/BaseEntity.cs
namespace DapperSampleProject.Models
{
    public class BaseEntity
    {
        public int Id { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
    }
}

DapperSampleProject/Models/Doctor.cs
namespace DapperSampleProject.Models
{
    public class Doctor:BaseEntity
    {
      
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Department { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string FullName { get { return this.Name + " " + this.Surname; } }
        public virtual ICollection<Patient> Patients { get; set; }

    }
}

DapperSampleProject/Models/ErrorViewModel.cs
namespace DapperSampleProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DapperSampleProject/Models/Patient.cs
namespace DapperSampleProject.Models
{
    public class Patient : BaseEntity
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string IdentityNumber { get; set; }
        public string Disease { get; set; }
        public Doctor Doctor { get; set; }     
        public int DoctorId { get; set; }
    }
}

DapperSampleProject/Models/PatientWithDoctor.cs
namespace DapperSampleProject.Models
{
    public class PatientWithDoctor
    {
    }
}

DapperSampleProject/Controllers/DoctorController.cs
using DapperSampleProject.Models;
using DapperSampleProject.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Numerics;

namespace DapperSampleProject.Controllers
{
    public class DoctorController : Controller
    {
        private readonly DoctorRepository _doctorRepository;
        public DoctorController(DoctorRepository doctorRepository)
        {
            _doctorRepository = doctorRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _doctorRepository.GetAllAsync());
        }
        [HttpPost]
        public async Task<IActionResult> Save(Doctor doctor)
        {
            await _doctorRepository.AddAsync(doctor);
            return RedirectToAction(nameof(Index));

        }
        public IActionResult Save()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Update(Doctor doctor)
        {
            doctor.CreatedDate = _doctorRepository.GetByIdAsync(doctor.Id).GetAwaiter().GetResult().CreatedDate;
            _doctorRepository.Update(doctor);
            return RedirectToAction(nameof(Index));

        }
        public async Task<IActionResult> Update(int id)
        {
            var doctor = await _doctorRepository.GetByIdAsync(id);
            return View(doctor);
        }
       
        public async Task<IActionResult> Remove(int id)
        {
            var doctor = await _doctorRepository.GetByIdAsync(id);
            _doctorRepository.Remove(doctor);
            return RedirectToAction(nameof(Index));

        }

    }
}

DapperSampleProject/Controllers/HomeController.cs
using DapperSampleProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DapperSampleProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DapperSampleProject/Controllers/PatientController.cs
using DapperSampleProject.Models;
using DapperSampleProject.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Numerics;

namespace DapperSampleProject.Controllers
{
    public class PatientController : Controller
    {
        private readonly PatientRepository _patientRepository;
        private readonly DoctorRepository _doctorRepository;
        public PatientController(PatientRepository patientRepository, DoctorRepository doctorRepository)
        {
            _patientRepository = patientRepository;
            _doctorRepository = doctorRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _patientRepository.GetAllAsync());
        }

        public async Task<IActionResult> Save()
        {
            var doctors = await _doctorRepository.GetAllAsync();

            ViewBag.doctors = new SelectList(doctors, "Id", "FullName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Save(Patient patient)
        {
            await _patientRepository.AddAsync(patient);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int id)
        {
            var patient = await _patientRepository.GetByIdAsync(id);

            var doctors = await _doctorRepository.GetAllAsync();

            ViewBag.doctors = new SelectList(doctors, "Id", "FullName");

            return View(patient);
        }

        [HttpPost]
        public IActionResult Update(Patient patient)
        {
            patient.CreatedDate = _doctorRepository.GetByIdAsync(patient.DoctorId).GetAwaiter().GetResult().CreatedDate;
            _patientRepository.Update(patient);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(Patient patient)
        {
            _patientRepository.Remove(patient);
            return RedirectToAction(nameof(Index));
        }
    }
}

DapperSampleProject/Views/Doctor/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model List<Doctor>
<a class="btn btn-success" asp-controller="Doctor" asp-action="Save">Save Doctor</a>
<table class="table table-striped">
    <thead>
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Surname</td>
            <td>Department</td>
            <td>Phone Number</td>
            <td>Email</td>       
            <td>CreatedDate</td>
            <td>Actions</td>

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Surname</td>
                <td>@item.Department</td>
                <td>@item.PhoneNumber</td>
                <td>@item.Email</td>
                <td>@item.CreatedDate</td>
                <td>
                    <a class="btn btn-warning" asp-controller="Doctor" asp-action="Update" asp-route-id="@item.Id">Update</a>
                    <a class="btn btn-danger" asp-controller="Doctor" asp-action="Remove" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }

    </tbody>



</table>

DapperSampleProject/Views/Doctor/Save.cshtml
@{
    ViewData["Title"] = "Save";
}
@model Doctor
<h1>Save Doctor</h1>

<div class="row">

    <div class=col-md-6>

        <form asp-action="Save" method="post" asp-controller="Doctor">

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Surname"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>


            <div class="form-group mt-3">

                <input type="submit" value="Save" class="btn-primary rounded-2" />

            </div>
        </form>



    </div>


</div>

DapperSampleProject/Views/Doctor/Update.cshtml
@{
    ViewData["Title"] = "Save";
}
@model Doctor
<h1>Update Doctor</h1>

<div class="row">

    <div class=col-md-6>

        <form asp-action="Update" method="post" asp-controller="Doctor">

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Surname"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
          
             <div class="form-group mt-3">

                <input type="submit" value="Update" class="btn-primary rounded-2" />

            </div>
        </form>



    </div>


</div>

DapperSampleProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

DapperSampleProject/Views/Patient/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model List<Patient>
<a class="btn btn-success" asp-controller="Patient" asp-action="Save">Save Patient</a>
<table class="table table-striped">
    <thead>
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Surname</td>
            <td>IdentityNumber</td>
            <td>Disease</td>
            <td>Doctor</td>
            <td>CreatedDate</td>
            <td>Actions</td>

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Surname</td>
                <td>@item.IdentityNumber</td>
                <td>@item.Disease</td>
                <td>@item.Doctor.Name @item.Doctor.Surname</td>
                <td>@item.CreatedDate</td>
                <td>
                    <a class="btn btn-warning" asp-controller="Patient" asp-action="Update" asp-route-id="@item.Id">Update</a>
                    <a class="btn btn-danger" asp-controller="Patient" asp-action="Remove" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }

    </tbody>



</table>

DapperSampleProject/Views/Patient/Save.cshtml
@{
    ViewData["Title"] = "Save";
}
@model Patient
<h1>Save Patient</h1>

<div class="row">

    <div class=col-md-6>

        <form asp-action="Save" method="post" asp-controller="Patient">

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Surname"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IdentityNumber"></label>
                <input asp-for="IdentityNumber" class="form-control" />
                <span asp-validation-for="IdentityNumber" class="text-danger"></span>
            </div>

             <div class="form-group">
                <label asp-for="Disease"></label>
                <input asp-for="Disease" class="form-control" />
                <span asp-validation-for="Disease" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Doctor</label>
                <select asp-for="DoctorId" asp-items="ViewBag.doctors" class="form-control"></select>

            </div>

            <div class="form-group">

                <input type="submit" value="Save" class="btn-primary rounded-2 mt-2" />

            </div>
        </form>



    </div>


</div>

DapperSampleProject/Views/Patient/Update.cshtml
@{
    ViewData["Title"] = "Save";
}
@model Patient
<h1>Update Patient</h1>

<div class="row">

    <div class=col-md-6>

        <form asp-action="Update" method="post" asp-controller="Patient">

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Surname"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IdentityNumber"></label>
                <input asp-for="IdentityNumber" class="form-control" />
                <span asp-validation-for="IdentityNumber" class="text-danger"></span>
            </div>

             <div class="form-group">
                <label asp-for="Disease"></label>
                <input asp-for="Disease" class="form-control" />
                <span asp-validation-for="Disease" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Doctor</label>
                <select asp-for="DoctorId" asp-items="ViewBag.doctors" class="form-control"></select>

            </div>

            <div class="form-group">

                <input type="submit" value="Save" class="btn-primary rounded-2 mt-2" />

            </div>
        </form>



    </div>


</div>

DapperSampleProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DapperSampleProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DapperSampleProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DapperSampleProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Doctors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="Index">Patients</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>